### PR TITLE
Add pdal to comparisons

### LINKED ISSUE #23: Add PDAL to comparison matrix
As a part of https://github.com/openjournals/joss-reviews/issues/7123, I used both **startinpy** and [PDAL](https://pdal.io) to create a terrain mesh from a [USGS 3DEP](https://www.usgs.gov/3d-elevation-program) point cloud. PDAL uses [delaunator-cpp](https://github.com/delfrrr/delaunator-cpp) for its triangulation, wrapped in [filters.delaunay](https://pdal.io/en/2.7.2/stages/filters.delaunay.html). Because PDAL has a [Python API](https://github.com/PDAL/python?tab=readme-ov-file) and has good performance, it might be good to include it in the [comparisons](https://github.com/hugoledoux/startinpy/tree/master/dt_comparisons). ~I can't add it to the comparisons myself because they use @hugoledoux local files.~ EDIT: I see that there's links to download the performance testing files, so I'm going to take a stab at adding PDAL myself 🙇🏼.

I don't want to assume that I'm doing things correctly, but in my tests I found that **PDAL** + **delaunator-cpp** was significantly faster in a simple build-terrain operation. I did my best to ensure that I was using a release profile when building **startinpy** but of course could have made an error.

cc @kylemann16 who is a **PDAL** developer.

## Comparison

I compared performance using a tiled [COPC](https://copc.io/), fetched from Microsoft's [Planetary Computer](https://planetarycomputer.microsoft.com/) using [stac-cli](https://crates.io/crates/stac-cli), [jq](https://jqlang.github.io/jq/), and [stac-asset](https://github.com/stac-utils/stac-asset):

```shell
stac search https://planetarycomputer.microsoft.com/api/stac/v1 \
    -c 3dep-lidar-copc \
    --intersects '{"type":"Point","coordinates":[-105.119,40.173]}' \
    | jq '.features[0]' \
    | stac-asset download
```

### **startinpy**

<details>
<summary>Code</summary>

```python
import time

import laspy
import numpy

import startinpy

start = time.time()
las = laspy.read("USGS_LPC_CO_SoPlatteRiver_Lot2a_2013_13TDE489446_LAS_2015.copc.laz")
points = las.points[las.classification == 2]
points = numpy.stack((points.x, points.y, points.z)).transpose()

read = time.time()
dt = startinpy.DT()
dt.insert(points)

created = time.time()
dt.write_ply("dt-startinpy.ply")

done = time.time()

print(f"Read:   {read - start:.3f}s")
print(f"Create: {created - read:.3f}s")
print(f"Write:  {done - created:.3f}s")
print(f"Total:  {done - start:.3f}s")
```
</details>

```text
Read:   2.320s
Create: 43.147s
Write:  7.384s
Total:  52.851s
```

### **PDAL**

<details>
<summary>Code</summary>

```python
import time

from pdal import Filter, Reader

pipeline = Reader.las(
    filename="USGS_LPC_CO_SoPlatteRiver_Lot2a_2013_13TDE489446_LAS_2015.copc.laz"
) | Filter.range(limits="Classification[2:2]")

start = time.time()
pipeline.execute()

read = time.time()
pipeline = Filter.delaunay().pipeline(pipeline.arrays[0])
pipeline.execute()

created = time.time()
mesh = pipeline.get_meshio(0)
mesh.write("dt-pdal.ply")

done = time.time()

print(f"Read:   {read - start:.3f}s")
print(f"Create: {created - read:.3f}s")
print(f"Write:  {done - created:.3f}s")
print(f"Total:  {done - start:.3f}s")
```
</details>

```text
Read:   3.916s
Create: 3.943s
Write:  1.128s
Total:  8.987s
```

### QC

<details>
<summary>Comparing statistics</summary>

```shell
$ pdal info dt-startinpy.ply | jq .stats.statistic 
[
  {
    "average": 489726.2401,
    "count": 2872483,
    "maximum": 490500,
    "minimum": 489000,
    "name": "X",
    "position": 0,
    "stddev": 432.9948745,
    "variance": 187484.5614
  },
  {
    "average": 4446745.876,
    "count": 2872483,
    "maximum": 4447500,
    "minimum": 4446000,
    "name": "Y",
    "position": 1,
    "stddev": 439.3933042,
    "variance": 193066.4758
  },
  {
    "average": 1533.628089,
    "count": 2872483,
    "maximum": 1554.64,
    "minimum": 1515.02,
    "name": "Z",
    "position": 2,
    "stddev": 7.959375129,
    "variance": 63.35165245
  }
]
$ pdal info dt-pdal.ply | jq .stats.statistic
[
  {
    "average": 489726.2391,
    "count": 2872606,
    "maximum": 490500,
    "minimum": 489000,
    "name": "X",
    "position": 0,
    "stddev": 432.996162,
    "variance": 187485.6763
  },
  {
    "average": 4446745.877,
    "count": 2872606,
    "maximum": 4447500,
    "minimum": 4446000,
    "name": "Y",
    "position": 1,
    "stddev": 439.392411,
    "variance": 193065.6908
  },
  {
    "average": 1533.628108,
    "count": 2872606,
    "maximum": 1554.64,
    "minimum": 1515.02,
    "name": "Z",
    "position": 2,
    "stddev": 7.959359551,
    "variance": 63.35140446
  }
]
```
</details>

<details>
<summary>Images from QGIS</summary>

The input point cloud:

copc

The output mesh (both **startinpy** and **PDAL** produced the same-enough output):

ply
</details>

### PR DESCRIPTION
**Pull request by gadomski**
- Closes #23 

Includes some additional fixups:

- Adds download script for laz files
- Adds a requirements file for comparison dependencies
- Does some minor, non-functional cleanups to the comparisons (e.g. removing unused assignments)

I ran the comparisons locally, and my times were much slower than was is currently contained in the README, so I'm guessing that the comparisons were originally run on some heavier metal than my little laptop. As such, I have _not_ updated the table, but will leave that to ~@evetion~ @hugoledoux .

Here's a couple of the benchmarks from a local run:

| library |random_10k|random_50k|dem.tiff|LAZ_2M|LAZ_33M|
|---------|----------|----------|--------|------|-------|
|startinpy|   0.038  |   0.447  |  1.040 | 9.243|151.183|
| triangle|   0.011  |   0.039  |  0.371 | 1.910| 37.363|
|   pdal  |   0.009  |   0.031  |  0.166 | 3.233| 85.006|

### CODE REVIEW

**Comment by evetion** [comment]
@gadomski Did you mean to ping me? I'm missing the context here.

**Comment by hugoledoux** [comment]
I had never realised that PDAL contains a Delaunay triangulator, and that the code is Delaunator written in CPP. Many thanks for pointing this out!

So you editor makes a lot of small changes to my files, so I took the pdal function and added it to my script. And I cleaned, sorry it was indeed a small mess with old imports and no download and no `requirements.txt`. 

Now it's okay, and I pushed to master.

Your computer is indeed slower than mine: what do OS do you use actually? I'm on macOS, M3 Pro and 36GB of RAM.

The results I obtained are somewhat the same proportions as yours, except the GeoTIFF files I get nearly 30s and you get 0.166s... I checked the code, and I don't see what is wrong or what could happen. Any ideas?

**Comment by gadomski** [comment]
> @gadomski Did you mean to ping me? I'm missing the context here.

Nope, wrong `@`, many apologies.

**Comment by gadomski** [comment]
> So you editor makes a lot of small changes to my files

Apologies for that, that's my fault.

> Now it's okay, and I pushed to master.

Ok, I'll close this PR as Overcome By Events.

> what OS do you use actually? I'm on macOS, M3 Pro and 36GB of RAM.

Mac, 2 GHz Quad-Core Intel Core i5, 16GB RAM ... so smol :-).

> GeoTIFF files I get nearly 30s and you get 0.166s... I checked the code, and I don't see what is wrong or what could happen. Any ideas?

That is surprising, and I don't have any immediate thoughts, though I can hopefully take a look today.

**Pull request closed without merging**
